### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Damlaozer06**

### CODE REVIEW

**Review by SteveLoev — APPROVED** [review]
nice job

**Review by aliyag19 — APPROVED** [review]
Thank you!

**Review by Zoiazakharova — APPROVED** [review]
good Job!

**Comment by Damlaozer06** [comment]
can you please do the resolve conflicts part ??? I have no idea why I am getting this conflict over and over every time I fetch and pull the project!! thanks a lot guys!!

**Review by SteveLoev — APPROVED** [review]
reviewed!

**Review by JohnMadonna — CHANGES_REQUESTED** [review]
please match .gitignore

**Pull request closed without merging**
